### ISSUE TITLE
User install does not enable encryption of root partition

### ISSUE THREAD

**Issue by kylerankin** [purism/PureOS-ISO#1]
Expected behavior: After the initial OEM install goes through and the user goes through their customized OS install, the installer should prompt the user for their disk encryption passphrase and enable disk encryption on the installed OS root partition. Since full disk encryption is used, the installer will need to also create a separate /boot partition.

Actual behavior: The user install does not prompt for an encryption passphrase and installs the OS without disk encryption.

**Comment by zgrimshell** [comment]
Notice that Debian doesn't yet have OEM install but some work/porting has been on it and the future will show us, instead I guess you are aiming on preesed file.

So AFAIR just passing the crypto in preseed file where partitioning should happen should be enough to make all this work (I didn't do this in some time nor tested but I think it didn't change)

**Comment by kylerankin** [comment]
Actually getting crypto to work is relatively straightforward and documented for preseed, but preseeding away the automatic wiping of the disk (which could take some time for a user, and which Todd has discussed wanting to preseed away) isn't. I've done some work on this front for the team already at https://github.com/kylerankin/pureos-preseed which you can reference to see what I did. Unfortunately preseeding away that disk wipe process required a live patch of the md-crypto code during the install.

**Comment by adrian-purism** [comment]
Hello Kyle can we close this issue since you tested the latest ISO and it looks fine, the encryption part i mean

**Comment by adrian-purism** [comment]
http://repo.puri.sm/pureos/iso/test/PureOS-2.0_test_crypt.iso this ISO fix the encryption issue
