### ISSUE TITLE
No option to reinstall PureOS in grub after user install

### ISSUE THREAD

**Issue by kylerankin** [purism/PureOS-ISO#2]
Expected behavior: When the user completes the PureOS install and reboots, they should see an option at the bottom of the list of Grub options that lets them re-install PureOS from the recovery disk that's on their drive. This allows them to get a factory reinstall whenever they want.

Actual behavior: After the user install completes, the Grub menu only lists options to boot into PureOS, no install options are present in the menu.

**Comment by hemaprathaban** [comment]
we have added Factory reset option to reinstall PureOS in our latest ISO

http://repo.puri.sm/pureos/iso/test/PureOS-2.0-OEM-20160117.iso
