### ISSUE TITLE
Install enables root account

### ISSUE THREAD

**Issue by kylerankin** [purism/PureOS-ISO#3]
During the install, the user is prompted for a root password. Whether or not this is the default for a Debian install (no disk encryption is also a default for a Debian install), it is a better security practice to have the root password disabled altogether, and for the user to use sudo whenever they want root access.

**Comment by zgrimshell** [comment]
That is the default option in d-i but it also has nice description saying what and why happens when you choose to *not* have root pass and also it says that the normal account will in that case gain sudo powers. Just use this in preseed file:

d-i passwd/root-login boolean false

**Comment by kylerankin** [comment]
I'm aware it can be preseeded away, but what I'm suggesting is that the PureOS install disable the root account by default. since PureOS is specifically focused on security and a disabled root account that relies on sudo instead, is a more secure default.

**Comment by zgrimshell** [comment]
IMHO preseeding it is the correct way to disable it. Agree on why it should be disabled.

**Comment by hemaprathaban** [comment]
We enable root login for user.
