### ISSUE TITLE
Hostname is preseeded away during install

### ISSUE THREAD

**Issue by kylerankin** [purism/PureOS-ISO#4]
Most users will probably want to set a custom hostname when installing an OS on their machine. The installer preseeds this option away.

**Comment by zgrimshell** [comment]
Hm, not sure I understand correctly with the part "installer preseeds this option away". I assume you say it doesn't show the window for user to type his/her own hostname? If the answer is yes then - Debian Installer does show by default hostname option (it populates it with what it gets from DHCP) but user can just change it and continue with installation.

**Comment by kylerankin** [comment]
Correct, I wasn't asked for my hostname during the PureOS install, however I do normally get presented with it during a standard Debian install. Just to be clear, I'm referring to my experience with the OEM install ISO that installs onto a partition on the Librem and then presents an "Install PureOS" GRUB menu option to the user afterwards.

**Comment by zgrimshell** [comment]
I just now found the preseed.cfg used for PureOS and indeed it doesn't have that option! Thanks for raising this issue (I didn't try it myself, just assumed it used d-i as it is).

**Comment by adrian-purism** [comment]
We tested together with hema and this ISO works fine related with this issue:
http://repo.puri.sm/pureos/iso/test/PureOS-2.0_test_crypt.iso

**Comment by adrian-purism** [comment]
sorry confused this issue with domain name, am re open it this issue

**Comment by adrian-purism** [comment]
we manage to fix this with the follow setting in the pressed:
d-i netcfg/hostname string purism   
instead of: 
#d-i netcfg/get_hostname string purism

**Comment by adrian-purism** [comment]
http://repo.puri.sm/pureos/iso/test/PureOS-2.0-Desktop-01_11_2016.iso
this iso it will fix this issue
